#!/usr/bin/env bash

# regex to validate in commit msg
commit_regex='(tl-[0-9]+|merge)'
error_msg="Aborting commit. Your commit message is missing a JIRA Issue Number ('tl-1111') '"
rm -rf fl.txt
echo $1 >> fl.txt
fil="fl.txt"

if ! grep -iE $commit_regex $fil; then
    echo "$error_msg" >&2
    exit 1
fi
rm -rf fl.txt